# Generated by Django 6.0 on 2025-12-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='member_id',
        ),
    ]
