# Generated by Django 6.0 on 2025-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pages', models.IntegerField()),
                ('publication_year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(default='French', max_length=50)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, upload_to='book_covers/')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('borrowed', 'Emprunté'), ('reserved', 'Réservé'), ('maintenance', 'En maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx')],
            },
        ),
    ]
