# Generated by Django 6.0 on 2025-12-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('position_in_queue', models.IntegerField()),
                ('estimated_availability', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('normal', 'Normale'), ('low', 'Basse')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book')),
            ],
            options={
                'ordering': ['position_in_queue'],
            },
        ),
    ]
