# Generated by Django 6.0 on 2025-12-19 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='estimated_availability',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='priority',
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='position_in_queue',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ready', 'Prêt à récupérer'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20),
        ),
    ]
