# Generated by Django 6.0 on 2025-12-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'En cours'), ('returned', 'Retourné'), ('overdue', 'En retard')], default='active', max_length=20)),
                ('renewable_count', models.IntegerField(default=2)),
                ('renewed_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book')),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
    ]
